/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditActivityWindow.java
 *
 * Created on 18 nov. 2011, 09:59:18
 */
package sequence.ui.window;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import sequence.model.Actuator;
import sequence.model.Note;
import sequence.model.Sequence;
import sequence.model.activity.Action;
import sequence.model.activity.Activity;
import sequence.model.activity.AnatomicStructure;
import sequence.processor.ActivityChange;
import sequence.processor.Processor;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author jordan
 */
public class EditActivityWindow extends javax.swing.JFrame {
    private Sequence sequence;

    /** Creates new form EditActivityWindow */
    public EditActivityWindow() {
        initComponents();
    }
    public EditActivityWindow(final MainWindow mainWindow, final Activity activity, final Sequence sequence) {
        this.sequence=sequence;
        initComponents();
        
        id.setText(Integer.toString(activity.getId()));
        stateEdit.setModel(new DefaultComboBoxModel(sequence.states()));
        disciplineEdit.setModel(new DefaultComboBoxModel(sequence.disciplines()));
        typeEdit.setModel(new DefaultComboBoxModel(sequence.types()));
        actuatorEdit.setText(activity.getActuator().toString());
        actionEdit.setText(activity.getAction().toString());
        usedInstrumentsEdit.setText(activity.getUsedInstrument().toString());
        anatomicStructureEdit.setText(activity.getTreatedStructure().toString());
        startTimeEdit.setText(Integer.toString(activity.getActivitytime().getStartTime()));
        endTimeEdit.setText(Integer.toString(activity.getActivitytime().getStopTime()));
        durationEdit.setText(Integer.toString(activity.getActivitytime().getDuration()));
        noteText.setText(activity.getNote().getNote());
        
        final JFrame frame = this;
        cancelButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setVisible(false);
            }
        });
        
        final Processor proc = mainWindow.getProcessor();
        saveButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Activity newActivity = new Activity(activity.getId(), activity.getState(), activity.getDiscipline(), activity.getType());
                newActivity.setAction(new Action(actionEdit.getText()));
                newActivity.setActuator(new Actuator());
                newActivity.setNote(new Note(noteText.getText()));
                newActivity.setTreatedStructure(new AnatomicStructure(anatomicStructureEdit.getText()));
                newActivity.getActivitytime().setDuration(Integer.parseInt(durationEdit.getText()));
                newActivity.getActivitytime().setStartTime(Integer.parseInt(startTimeEdit.getText()));
                newActivity.getActivitytime().setStopTime(Integer.parseInt(startTimeEdit.getText()));
                proc.Do(new ActivityChange(activity, newActivity));
                mainWindow.repaint();
                frame.setVisible(false);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        discipline = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        stateEdit = new javax.swing.JComboBox();
        disciplineEdit = new javax.swing.JComboBox();
        typeEdit = new javax.swing.JComboBox();
        actuator = new javax.swing.JLabel();
        actuatorEdit = new javax.swing.JTextField();
        action = new javax.swing.JLabel();
        usedInstruments = new javax.swing.JLabel();
        anatomicStructure = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        actionEdit = new javax.swing.JTextField();
        usedInstrumentsEdit = new javax.swing.JTextField();
        anatomicStructureEdit = new javax.swing.JTextField();
        noteEdit = new javax.swing.JScrollPane();
        noteText = new javax.swing.JTextArea();
        startTime = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        endTime = new javax.swing.JLabel();
        startTimeEdit = new javax.swing.JTextField();
        durationEdit = new javax.swing.JTextField();
        endTimeEdit = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        id = new javax.swing.JLabel();

        setTitle("Edit Activity");
        setAlwaysOnTop(true);

        title.setFont(new java.awt.Font("Tahoma", 1, 18));
        title.setText("Activity Edition");

        state.setText("State");

        discipline.setText("Discipline");

        type.setText("Type");

        stateEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        disciplineEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        typeEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        actuator.setText("Actuator");

        actuatorEdit.setText("Actuator");

        action.setText("Action");

        usedInstruments.setText("Used Instruments");

        anatomicStructure.setText("AnatomicStructure");

        note.setText("Note");

        actionEdit.setText("action");

        usedInstrumentsEdit.setText("usedInstruments");

        anatomicStructureEdit.setText("anatomicStructure");

        noteText.setColumns(20);
        noteText.setRows(5);
        noteText.setText("note");
        noteEdit.setViewportView(noteText);

        startTime.setText("Start time");

        duration.setText("Duration");

        endTime.setText("End time");

        startTimeEdit.setText("startTime");

        durationEdit.setText("duration");

        endTimeEdit.setText("endTime");

        saveButton.setText("OK");

        cancelButton.setText("Cancel");

        id.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noteEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(state)
                            .addComponent(discipline)
                            .addComponent(type)
                            .addComponent(actuator)
                            .addComponent(action)
                            .addComponent(usedInstruments)
                            .addComponent(anatomicStructure)
                            .addComponent(note))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stateEdit, 0, 299, Short.MAX_VALUE)
                            .addComponent(disciplineEdit, javax.swing.GroupLayout.Alignment.LEADING, 0, 299, Short.MAX_VALUE)
                            .addComponent(typeEdit, javax.swing.GroupLayout.Alignment.LEADING, 0, 299, Short.MAX_VALUE)
                            .addComponent(actuatorEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(actionEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(usedInstrumentsEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(anatomicStructureEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startTime)
                            .addComponent(duration)
                            .addComponent(endTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endTimeEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(durationEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(startTimeEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                        .addComponent(id)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(state)
                    .addComponent(stateEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discipline)
                    .addComponent(disciplineEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type)
                    .addComponent(typeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actuator)
                    .addComponent(actuatorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(action)
                    .addComponent(actionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usedInstruments)
                    .addComponent(usedInstrumentsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anatomicStructure)
                    .addComponent(anatomicStructureEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(note)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTime)
                    .addComponent(startTimeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duration)
                    .addComponent(durationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endTime)
                    .addComponent(endTimeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditActivityWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action;
    private javax.swing.JTextField actionEdit;
    private javax.swing.JLabel actuator;
    private javax.swing.JTextField actuatorEdit;
    private javax.swing.JLabel anatomicStructure;
    private javax.swing.JTextField anatomicStructureEdit;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel discipline;
    private javax.swing.JComboBox disciplineEdit;
    private javax.swing.JLabel duration;
    private javax.swing.JTextField durationEdit;
    private javax.swing.JLabel endTime;
    private javax.swing.JTextField endTimeEdit;
    private javax.swing.JLabel id;
    private javax.swing.JLabel note;
    private javax.swing.JScrollPane noteEdit;
    private javax.swing.JTextArea noteText;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel startTime;
    private javax.swing.JTextField startTimeEdit;
    private javax.swing.JLabel state;
    private javax.swing.JComboBox stateEdit;
    private javax.swing.JLabel title;
    private javax.swing.JLabel type;
    private javax.swing.JComboBox typeEdit;
    private javax.swing.JLabel usedInstruments;
    private javax.swing.JTextField usedInstrumentsEdit;
    // End of variables declaration//GEN-END:variables
}
